#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Ensure custom exists
mkdir $BASEDIR/custom &> /dev/null
# Ensure dependancies are installed.
errors=()
for prog in zsh curl chsh git tar
do
    if ! command -v $prog &> /dev/null
    then
        errors+=($prog)
    fi
done
if [ ${#errors[@]} -ne 0 ]
then
    echo "The programs below are missing! Please install them first."
    echo "${errors[@]}"
    if [ "$IGNORE_PREFLIGHT" == "1" ]
    then
        echo "The preflight is being ignored due to the env. Procceed with caution."
        exit 0
    fi
    echo 'If your sure you know what your doing, you may bypass this with "IGNORE_PREFLIGHT=1".'
    exit 1
fi
