#!/usr/bin/env bash
ask () {
    if [ -z $3 ] && ! $3
    then
        read -p "$1 " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            $2
        fi
    fi
}

ask "Do you want to install nvm?" "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash" $(command -v dnvm &> /dev/null)
ask "empty" "echo empty"
ask "true" "echo true" true
ask "false" "echo false" false
